const express = require('express');
const router= express.Router();
const userController = require('../controllers/userController');
const { userSchema } = require('../validator/userValidator');
const { validate } = require('../middleware/validateMiddleware');
router.post('/', validate(userSchema),userController.createUser);
router.get('/', userController.getAllUsers);
router.get('/:id', userController.getUser);
router.put('/:id',validate(userSchema), userController.updateUser);
router.delete('/:id', userController.deleteUser);
module.exports = router;